from sys import argv, stderr, exit as sys_exit
import dashboard
from os import path

mode = dashboard.LIVE

if len(argv) not in [2, 3] \
        or (argv[1] == "replay" and len(argv) != 3) \
        or (argv[1] == "live" and len(argv) != 2) \
        or argv[1] not in ["live", "replay"]:
    print(
        "The arguments you specified are invalid.\n"
        "Usage : $PYTHON_INTERPRETER dashboard.py <live|replay> [path_to_replay_file]",
        file=stderr
    )
    sys_exit(1)

if argv[1] == "replay" and len(argv) == 3:
    mode = dashboard.REPLAY
    if not(path.isfile(argv[2])):
        print("The file you specified does not exist.", file=stderr)
        sys_exit(1)
    if not(argv[2].endswith(".csv")):
        print("The file you provided does not seem to be a CSV file.", file=stderr)
        sys_exit(1)

csv_header = ""

if mode == dashboard.REPLAY:
    with open(argv[2], 'r') as f:
        lines = f.readlines()
        if lines[0] != csv_header:
            print("The file you provided does not seem to be generated by our services.", file=stderr)
            sys_exit(1)
        for line in lines[1:]:
            pass


